# Generated by Django 5.1 on 2024-08-11 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTeamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_committed', models.DateField(verbose_name='date committed')),
                ('count', models.PositiveIntegerField(blank=True, default=1, verbose_name='count')),
                ('habit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_team_logs', to='api.habititem', verbose_name='habit item')),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev', to='api.habitteamlog', verbose_name='next habit team log')),
            ],
        ),
    ]
