# Generated by Django 5.1 on 2024-08-10 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitstatus',
            name='committed_at',
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='date_committed',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date committed'),
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev', to='api.habitstatus', verbose_name='next habit status'),
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='time_committed',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='time committed'),
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_committed', models.DateTimeField(auto_now_add=True, verbose_name='date committed')),
                ('habit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to='api.habititem', verbose_name='habit item')),
            ],
        ),
    ]
