# Generated by Django 5.1 on 2024-08-10 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitlog",
            name="committed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committed_habit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="count",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="count"
            ),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="next",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prev",
                to="api.habitlog",
                verbose_name="next habit log",
            ),
        ),
        migrations.AlterField(
            model_name="habitlog",
            name="date_committed",
            field=models.DateField(verbose_name="date committed"),
        ),
    ]
