# Generated by Django 5.1 on 2024-08-12 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_habitlog_committed_by_habitlog_count_habitlog_next_and_more"),
        ("api", "0002_habitteamlog"),
    ]

    operations = []
