# Generated by Django 5.1 on 2024-08-10 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_habitlog_count_habitlog_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='committed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committed_habit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
