# Generated by Django 5.1 on 2024-08-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitstatus',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev', to='api.habitstatus', verbose_name='next habit status'),
        ),
    ]
