# Generated by Django 5.1 on 2024-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habitstatus_count_habitstatus_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitstatus',
            name='committed_at',
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='date_committed',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date committed'),
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='time_committed',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='time committed'),
        ),
    ]
