# Generated by Django 5.1 on 2024-08-08 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habititem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='habititem',
            name='notification_settings',
        ),
        migrations.RemoveField(
            model_name='habititem',
            name='sharing_settings',
        ),
        migrations.RemoveField(
            model_name='habititem',
            name='user',
        ),
        migrations.AddField(
            model_name='habititem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habititem',
            name='name',
            field=models.CharField(default='Some habit', max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='habititem',
            name='frequency',
            field=models.PositiveIntegerField(verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='User', max_length=256, verbose_name='nickname'),
        ),
    ]
