# Generated by Django 5.0.8 on 2024-08-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habitlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
