# Generated by Django 5.1 on 2024-08-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_habitlog_unique_together_alter_habitlog_date"),
        ("api", "0003_remove_habitstatus_committed_at_and_more"),
    ]

    operations = []
