# Generated by Django 5.0.8 on 2024-08-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_habitlog_unique_together_alter_habitlog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habititem',
            name='frequency',
        ),
    ]
