# Generated by Django 5.1 on 2024-08-08 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_habititem_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitstatus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='habitstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='habitstatus',
            name='time',
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='commited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='commited at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='commited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitstatus',
            name='state',
            field=models.CharField(choices=[('SC', 'succeeded'), ('SK', 'skipped'), ('FL', 'failed')], default='SC', max_length=2, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='habititem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitstatus',
            name='habit_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.habititem'),
        ),
    ]
