# Generated by Django 5.1 on 2024-08-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_habitlog_committed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date_committed',
            field=models.DateField(auto_now_add=True, verbose_name='date committed'),
        ),
    ]
