# Generated by Django 5.1 on 2024-08-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_habitstatus_date_remove_habitstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habit_items',
            field=models.ManyToManyField(blank=True, to='api.habititem', verbose_name='habit items'),
        ),
    ]
