# Generated by Django 5.1 on 2024-08-09 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_habit_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habititem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_habit_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitstatus',
            name='commited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='committed_habit_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitstatus',
            name='habit_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='committed_habit_status', to='api.habititem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='habit_items',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='api.habititem', verbose_name='habit items'),
        ),
        migrations.CreateModel(
            name='UsersHabitItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habititem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
