# Generated by Django 5.1 on 2024-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_habitlog_date_committed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date_committed',
            field=models.DateField(verbose_name='date committed'),
        ),
    ]
