# Generated by Django 5.1 on 2024-08-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_habititem_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersHabitItems',
        ),
    ]
