# Generated by Django 5.1 on 2024-08-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_habit_items_user_friends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitstatus',
            old_name='commited_at',
            new_name='committed_at',
        ),
        migrations.RenameField(
            model_name='habitstatus',
            old_name='commited_by',
            new_name='committed_by',
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_habit_items',
            field=models.ManyToManyField(blank=True, related_name='committing_users', to='api.habititem', verbose_name='joined habit items'),
        ),
    ]
